local_costmap:
  global_frame: map #map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 0.5 #2.0
  #static_map: false
  inflation_radius: 0.2 #0.5
  rolling_window: true
  width: 1.5 #1.5
  height: 1.5 #1.5
  resolution: 0.05
  tranceform_tolerance: 1.0
  plugins:
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  obstacle_layer:
    observation_sources: scan #laser
    scan: {topic: scan, data_type: LaserScan, expected_update_rate: 2.0, observation_persistence: 0.0, marking: true, clearing: true}
    #laser: {topic: scan, data_type: LaserScan, expected_update_rate: 2.0, observation_persistence: 0.0, marking: true, clearing: true}
